version: "2"
run:
  concurrency: 2
  go: "1.25"
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: false
  allow-parallel-runners: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
    code-climate:
      path: code-quality-report.json
  path-prefix: ""
linters:
  enable:
    - funlen
    - gocognit
    - gosec
    - nilerr
    - nolintlint
    - tagliatelle
    - wastedassign
  settings:
    funlen:
      lines: 100
      statements: 60
    gocognit:
      min-complexity: 20
    nolintlint:
      require-explanation: true
      require-specific: false
      allow-unused: false
    tagliatelle:
      case:
        rules:
          json: snake
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
issues:
  uniq-by-line: true
formatters:
  exclusions:
    generated: lax
