# https://taskfile.dev

version: '3'

dotenv: [ '.env' ]

vars:
  LINTER_CONFIG: .golangci.yaml

tasks:
  install:tools:
    desc: Install go tools
    cmds:
      - go install tool

  lint:
    desc: Run golangci-lint
    deps: [ install:tools ]
    cmds:
      - golangci-lint run -c {{.LINTER_CONFIG}}

  gen:
    desc: Generate protobuf
    deps: [ install:tools ]
    cmds:
      - buf lint
      - buf format -w
      - buf generate